name: Commit Backend E2E
on:
  workflow_run:
    workflows: ['Commit Test']
    types:
      - completed

jobs:
  main:
    runs-on: ubuntu-latest
    container: node:lts-alpine3.15

    strategy:
      matrix:
        database-name:
          - postgres
        database-user:
          - postgres
        database-password:
          - mysecretpassword
        database-host:
          - database
        database-port:
          - 5432
        redis-host:
          - redis
        redis-port:
          - 6379

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        ports:
          - ${{ matrix.database-port }}:${{ matrix.database-port }}
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: yarn install

      - run: npx nx run test-e2e
        env:
          DATABASE_URL: postgres://${{ matrix.database-user }}:${{ matrix.database-password }}@${{ matrix.database-host }}:${{ matrix.database-port }}/${{ matrix.database-name }}
          REDIS_URL: redis://${{ matrix.redis-host }}:${{ matrix.redis-port }}
