name: 'Is code pretty & linted'
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Link dependencies for mobile app'
        run: |
          npx nx run mobile:install
          npx nx run mobile:sync-deps
          npx nx run mobile:ensure-symlink

      - name: "Check it's pretty"
        run: yarn prettier:check

      - name: "Check it's linted"
        run: npx nx run-many -t lint
